import nodemailer from "nodemailer";
import Shift from "../models/Shift.js";
import CoverRequest from "../models/CoverRequest.js";

const parseIntStrict = (value) => {
  const n = Number.parseInt(String(value), 10);
  return Number.isFinite(n) ? n : null;
};

const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: parseIntStrict(process.env.EMAIL_PORT) ?? 587,
  secure: false,
  auth: process.env.EMAIL_USER
    ? { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS }
    : undefined,
});

function buildCoverEmailHTML(gapShift) {
  return `
    <div style="font-family:Segoe UI,Arial,sans-serif;">
      <h2 style="margin:0 0 10px;">Cover required</h2>
      <p style="margin:0 0 10px;">A rota gap has been detected and requires cover.</p>
      <table style="border-collapse:collapse;font-size:13px;">
        <tr><td style="padding:6px 10px;border:1px solid #e5e7eb;background:#f9fafb;">Practice</td><td style="padding:6px 10px;border:1px solid #e5e7eb;">${gapShift.practice_id || ""}</td></tr>
        <tr><td style="padding:6px 10px;border:1px solid #e5e7eb;background:#f9fafb;">Date</td><td style="padding:6px 10px;border:1px solid #e5e7eb;">${String(gapShift.date || "").slice(0, 10)}</td></tr>
        <tr><td style="padding:6px 10px;border:1px solid #e5e7eb;background:#f9fafb;">Time</td><td style="padding:6px 10px;border:1px solid #e5e7eb;">${gapShift.start_time || ""} - ${gapShift.end_time || ""}</td></tr>
        <tr><td style="padding:6px 10px;border:1px solid #e5e7eb;background:#f9fafb;">Hours</td><td style="padding:6px 10px;border:1px solid #e5e7eb;">${gapShift.hours ?? ""}</td></tr>
        <tr><td style="padding:6px 10px;border:1px solid #e5e7eb;background:#f9fafb;">Clinical system</td><td style="padding:6px 10px;border:1px solid #e5e7eb;">${gapShift.clinical_system || ""}</td></tr>
      </table>
      <p style="margin:10px 0 0;color:#6b7280;font-size:12px;">Generated by CPS Intranet.</p>
    </div>
  `;
}

export async function runDailyGapDetection({ daysAhead = 14 } = {}) {
  const gaps = await Shift.findGapsAhead(daysAhead);

  const now = Date.now();
  const created = [];
  const skippedExisting = [];
  const emailed = [];

  for (const gap of gaps) {
    const gapId = gap.id || gap._id;
    if (!gapId) continue;

    const existing = await CoverRequest.findOpenByShiftId(gapId);
    if (existing) {
      skippedExisting.push(existing);
      continue;
    }

    const cover = await CoverRequest.create({
      shift_id: gapId,
      practice_id: gap.practice_id,
      practice_name: gap.practice_name || null,
      date: String(gap.date).slice(0, 10),
      start_time: gap.start_time,
      end_time: gap.end_time,
      hours_needed: gap.hours,
      clinical_system: gap.clinical_system,
      status: "open",
    });

    created.push(cover);

    const gapDate = new Date(`${String(gap.date).slice(0, 10)}T00:00:00Z`).getTime();
    const isOver48HoursAway = gapDate - now > 48 * 3600000;

    const opsEmail = String(process.env.OPS_EMAIL || "").trim();
    const canEmail = Boolean(process.env.EMAIL_HOST && (process.env.EMAIL_USER || !process.env.EMAIL_USER) && opsEmail);

    if (isOver48HoursAway && canEmail) {
      const html = buildCoverEmailHTML(gap);
      await transporter.sendMail({
        from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
        to: opsEmail,
        subject: `Cover required: ${String(gap.date).slice(0, 10)} (${gap.practice_id || ""})`,
        html,
      });

      const updated = await CoverRequest.markEmailSent(cover.id);
      emailed.push(updated || cover);
    }
  }

  return {
    daysAhead,
    totalGaps: gaps.length,
    coverRequestsCreated: created.length,
    coverRequestsExisting: skippedExisting.length,
    coverRequestEmailsSent: emailed.length,
  };
}

export function startGapDetectionScheduler({ intervalMs = 24 * 60 * 60 * 1000 } = {}) {
  let running = false;

  const tick = async () => {
    if (running) return;
    running = true;
    try {
      await runDailyGapDetection();
    } finally {
      running = false;
    }
  };

  setTimeout(tick, 10_000);
  const timer = setInterval(tick, intervalMs);

  return () => clearInterval(timer);
}
