import { createModel } from "../lib/model.js";

const PCN = createModel({
  modelName: "PCN",
  refs: {
    icb: { model: "ICB" },
    federation: { model: "Federation" },
    complianceGroup: { model: "DocumentGroup" },
    complianceGroups: { model: "DocumentGroup" },
    activeClinicians: { model: "User" },
    restrictedClinicians: { model: "User" },
    createdBy: { model: "User" },
  },
  defaults: {
    name: "",
    icb: null,
    federation: null,
    federationName: "",
    contacts: [],
    annualSpend: 0,
    contractType: "",
    contractStartDate: null,
    contractRenewalDate: null,
    contractExpiryDate: null,
    xeroCode: "",
    xeroCategory: "",
    activeClinicians: [],
    restrictedClinicians: [],
    documents: [],
    emailTemplates: [],
    monthlyMeetings: [],
    requiredSystems: {
      emis: false,
      systmOne: false,
      ice: false,
      accurx: false,
      docman: false,
      softphone: false,
      vpn: false,
      other: "",
    },
    ndaSigned: false,
    dsaSigned: false,
    mouReceived: false,
    gdprAgreement: false,
    welcomePackSent: false,
    govChecklist: false,
    insuranceCert: false,
    complianceDocs: {},
    complianceGroup: null,
    complianceGroups: [],
    groupDocuments: [],
    notes: "",
    isActive: true,
    createdBy: null,
    viewedBy: [],
  },
});

export default PCN;
