import { createModel } from "../lib/model.js";

const Practice = createModel({
  modelName: "Practice",
  refs: {
    pcn: { model: "PCN" },
    complianceGroup: { model: "DocumentGroup" },
    linkedClinicians: { model: "User" },
    restrictedClinicians: { model: "User" },
    createdBy: { model: "User" },
  },
  defaults: {
    name: "",
    pcn: null,
    odsCode: "",
    patientListSize: 0,
    address: "",
    city: "",
    postcode: "",
    contacts: [],
    linkedClinicians: [],
    restrictedClinicians: [],
    systemAccess: [],
    systemAccessNotes: "",
    contractType: "",
    fte: "",
    contractSignedDate: null,
    xeroCode: "",
    xeroCategory: "",
    cqcRating: false,
    indemnityInsurance: false,
    healthSafety: false,
    gdprPolicy: false,
    informationGovernance: false,
    ndaSigned: false,
    dsaSigned: false,
    mouReceived: false,
    welcomePackSent: false,
    mobilisationPlanSent: false,
    confidentialityFormSigned: false,
    prescribingPoliciesShared: false,
    remoteAccessSetup: false,
    templateInstalled: false,
    reportsImported: false,
    complianceDocs: {},
    complianceGroup: null,
    groupDocuments: [],
    documents: [],
    rotaVisible: true,
    notes: "",
    isActive: true,
    createdBy: null,
    viewedBy: [],
  },
});

export default Practice;
